@url = http://localhost:3000
@json = content-type: application/json


### 登入
POST {{url}}/login
{{json}}

{
    "username": "xiaokyo4",
    "password": "123456"
}

### 登出
get {{url}}/users/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDNjOGNmYTBiNzkwMWQ4NGZlNjJiZCIsImlhdCI6MTU1NzkwNzU5OX0.hdvc5smY4AgItMtXbUYOrqKwQgz9L3YVcWXFL8PZgro


### 注册
post {{url}}/register
{{json}}

{
    "username":"pokemengo1",
    "password":"123456"
}

### 获取用户信息
get {{url}}/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDNjOGNmYTBiNzkwMWQ4NGZlNjJiZCIsImlhdCI6MTU1NzkwNzU5OX0.hdvc5smY4AgItMtXbUYOrqKwQgz9L3YVcWXFL8PZgro

### 获取用户列表
get {{url}}/users/userlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDNjOGNmYTBiNzkwMWQ4NGZlNjJiZCIsImlhdCI6MTU1NzkwNzU5OX0.hdvc5smY4AgItMtXbUYOrqKwQgz9L3YVcWXFL8PZgro

### 修改用户信息
post {{url}}/users/updateUser
{{json}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjZDI3ZmY0OTUwNDc2MTc1NDc3ZWYyOSIsImlhdCI6MTU1NzI5OTE5Nn0.xw9hdXWYRpRKApjK0pAKq7MXATr1ipgqYXi3-CU_5sI

{
  "username":"zhengwenjian",
  "phone":"18989443542"
}