@url = http://localhost:3000
@json = content-type: application/json

### 获取用户列表
get {{url}}/

### 登入
POST {{url}}/login
{{json}}

{
    "username": "xiaokyo4",
    "password": "123456"
}

### 注册
post {{url}}/register
{{json}}

{
    "username":"xiaokyo4",
    "password":"123456"
}

### 获取用户信息
get {{url}}/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjY2Q3ZGRkZTUyZmUyMTVhMGY4YzRkZiIsImlhdCI6MTU1NzA1NzgyM30.WCH4m8a0Ao_Auoq1-eAGFluHQsN3C0OrxQUtiLaQAzQ

### 获取用户列表
get {{url}}/users/userlist
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjY2Q3ZGRkZTUyZmUyMTVhMGY4YzRkZiIsImlhdCI6MTU1NzA1NzgyM30.WCH4m8a0Ao_Auoq1-eAGFluHQsN3C0OrxQUtiLaQAzQ